apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx-service
  spec:
    ports:
    - protocol: TCP
      port: 80
    selector:
      app: nginx
- apiVersion: v1
  kind: Deployment
  metadata:
    name: nginx
    labels:
      app: nginx
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: nginx
      spec:
        serviceAccountName: nginx
        containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80