apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: nginx
    name: nginx
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: nginx
    name: nginx
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - events
    - endpoints
    - pods
    - nodes
    - componentstatuses
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app: nginx
    name: nginx
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: nginx
  subjects:
  - kind: ServiceAccount
    name: nginx
    namespace: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: metrics
    name: nginx-metrics
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: metrics
    name: nginx-metrics
  rules:
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    verbs:
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app: metrics
    name: nginx-metrics
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: nginx-metrics
  subjects:
  - kind: ServiceAccount
    name: nginx-metrics
    namespace: default
